dist: trusty
branches:
  only:
    - develop
    - master
language: python
python:
  - "2.6"
  - "2.7"
  - "3.6"
env:
  global:
    - ADDON_ID=plugin.video.filmix
before_install:
  - export PYTHONIOENCODING=UTF-8
  - wget -O /tmp/simplemedia.tar.gz https://github.com/vlmaksime/script.module.simplemedia/archive/master.tar.gz
  - tar -C /tmp -xf /tmp/simplemedia.tar.gz
  - ln -s /tmp/script.module.simplemedia-master/script.module.simplemedia/ script.module.simplemedia
install:
  - pip install -q codecov codacy-coverage mock future
  - pip install -q git+https://github.com/romanvm/script.module.simpleplugin.git
  - pip install -q git+https://github.com/vlmaksime/script.module.simplemedia.git
  - pip install -q https://github.com/vlmaksime/Kodistubs/archive/develop.zip
script:
  - coverage run tests.py
after_success:
  - codecov
  - coverage xml
  - python-codacy-coverage -r coverage.xml
before_deploy:
  - pip install -q git+https://github.com/romanvm/kodi-addon-submitter.git
  - submit-addon -s -z $ADDON_ID
  - export RELEASE_ZIP=$(ls *.zip)
deploy:
  # Publish an installable ZIP to GitHub Releases
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: $RELEASE_ZIP
    skip_cleanup: true
    on:
      tags: true
notifications:
  email: false