dist: trusty
branches:
  only:
    - develop
    - master
language: python
python:
  - "2.6"
  - "2.7"
  - "3.6"
before_install:
  - pip install https://github.com/romanvm/script.module.simpleplugin/archive/develop.zip
  - pip install https://github.com/vlmaksime/script.module.simplemedia/archive/master.zip
  - pip install https://github.com/vlmaksime/Kodistubs/archive/develop.zip
install:
  - pip install codecov codacy-coverage mock future
script:
  - coverage run tests.py
after_success:
  - codecov
  - coverage xml
  - python-codacy-coverage -r coverage.xml
